# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1c7eaf525e79202c82c6eea5fafb4fd6"
application_url = "https://unity-len-improve-delayed.trycloudflare.com"
embedded = true
name = "QRCode"
handle = "qrcode-264"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://unity-len-improve-delayed.trycloudflare.com/auth/callback",
  "https://unity-len-improve-delayed.trycloudflare.com/auth/shopify/callback",
  "https://unity-len-improve-delayed.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
